data:
  exp: 'stabilzation_train'
  checkpoints_dir: './checkpoint'
  log: './log'
  data_dir: './dataset_release'           
  use_cuda: true
  batch_size: 16
  resize_ratio: 0.25
  number_real: 10
  number_virtual: 2
  time_train: 2000  # ms
  sample_freq: 40   # ms
  channel_size: 1
  num_workers: 16                    # num_workers for data_loader
model:
  load_model:  null
  cnn:
    activate_function: relu         # sigmoid, relu, tanh, quadratic
    batch_norm: true
    gap: false
    layers:
  rnn:
    layers:  
    - - 512                        
      - true  
    - - 512                        
      - true    
  fc:
    activate_function: relu
    batch_norm: false               # (batch_norm and drop_out) is False
    layers:  
    - - 256                        
      - true  
    - - 4                         # last layer should be equal to nr_class
      - true
    drop_out: 0
train:
  no_flow: false
  optimizer: "adam"                  # adam or sgd
  momentum: 0.9                     # for sgd
  decay_epoch: null
  epoch: 400
  snapshot: 2
  init_lr: 0.0001
  lr_decay: 0.5
  lr_step: 200                       # if > 0 decay_epoch should be null
  seed: 1
  weight_decay: 0.0001
  clip_norm: False
  init: "xavier_uniform"            # xavier_uniform or xavier_normal
loss:
  follow: 10
  angle: 1
  smooth: 10 #10
  c2_smooth: 200 #20
  undefine: 2.0
  opt: 0.1
  stay: 0
lstm:
  moglstm: true
  mogGRU: false

transformer_or_rnn:
  transformer: false

flow_net:
  cnn: false
  cnn_vit: false
  vit: false
  tokenlearner_transforme: true

simCLR:
  is_use: true
  epoch_train_simCLR: 500
  batch_simCLR: 4
  feature_dim: 128
  num_workers: 16


